package electricekyc.tml.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.5.fuse.jdk11-800013
 * 2020-01-11T10:19:46.450+05:30
 * Generated source version: 3.3.5.fuse.jdk11-800013
 *
 */
@WebService(targetNamespace = "http://service.TML.ELECTRICeKYC/", name = "ELECTRICwsdl")
@XmlSeeAlso({ObjectFactory.class})
public interface ELECTRICwsdl {

    @WebMethod(operationName = "ELECTRICRequest")
    @RequestWrapper(localName = "ELECTRICRequest", targetNamespace = "http://service.TML.ELECTRICeKYC/", className = "electricekyc.tml.service.ELECTRICRequestObject")
    @ResponseWrapper(localName = "ELECTRICResponse", targetNamespace = "http://service.TML.ELECTRICeKYC/", className = "electricekyc.tml.service.ELECTRICResponseObject")
    public void electricRequest(

        @WebParam(name = "consent", targetNamespace = "")
        java.lang.String consent,
        @WebParam(name = "consumer_id", targetNamespace = "")
        java.lang.String consumerId,
        @WebParam(name = "service_provider", targetNamespace = "")
        java.lang.String serviceProvider,
        @WebParam(name = "name1", targetNamespace = "")
        java.lang.String name1,
        @WebParam(mode = WebParam.Mode.OUT, name = "KYC", targetNamespace = "")
        javax.xml.ws.Holder<KYCObject> kyc,
        @WebParam(mode = WebParam.Mode.OUT, name = "NameMatch", targetNamespace = "")
        javax.xml.ws.Holder<NameMatchObject> nameMatch
    );
}
