package electricekyc.tml.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.5.fuse.jdk11-800013
 * 2020-01-11T10:19:46.498+05:30
 * Generated source version: 3.3.5.fuse.jdk11-800013
 *
 */
@WebServiceClient(name = "ELECTRICwsdl",
                  wsdlLocation = "file:/C:/Users/swapnalitoraskar.ttl/workspace/prjTML_ELECTRICeKYC/src/main/resources/ELECTRICwsdl.wsdl",
                  targetNamespace = "http://service.TML.ELECTRICeKYC/")
public class ELECTRICwsdl_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.TML.ELECTRICeKYC/", "ELECTRICwsdl");
    public final static QName ELECTRICwsdlPort = new QName("http://service.TML.ELECTRICeKYC/", "ELECTRICwsdlPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/swapnalitoraskar.ttl/workspace/prjTML_ELECTRICeKYC/src/main/resources/ELECTRICwsdl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ELECTRICwsdl_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/swapnalitoraskar.ttl/workspace/prjTML_ELECTRICeKYC/src/main/resources/ELECTRICwsdl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ELECTRICwsdl_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ELECTRICwsdl_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ELECTRICwsdl_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ELECTRICwsdl_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ELECTRICwsdl_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ELECTRICwsdl_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ELECTRICwsdl
     */
    @WebEndpoint(name = "ELECTRICwsdlPort")
    public ELECTRICwsdl getELECTRICwsdlPort() {
        return super.getPort(ELECTRICwsdlPort, ELECTRICwsdl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ELECTRICwsdl
     */
    @WebEndpoint(name = "ELECTRICwsdlPort")
    public ELECTRICwsdl getELECTRICwsdlPort(WebServiceFeature... features) {
        return super.getPort(ELECTRICwsdlPort, ELECTRICwsdl.class, features);
    }

}
